# Utiliser une image de Python
FROM python:3.8-slim

# Définir le répertoireur
WORKDIR /app

# Copier le fichier et installer les dépendances
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copier le reste des fichiers dans le conteneur
COPY . .

# Exposer le port
EXPOSE 5000

# lancer l'application
CMD ["python", "app.py"]
